# from langchain_openai import ChatOpenAI
# from langchain_core.prompts import ChatPromptTemplate
# from langchain_core.output_parsers import StrOutputParser
# from langchain_community.llms import Ollama
import streamlit as st
import os
from dotenv import load_dotenv
from PIL import Image
import google.generativeai as genai

# Load environment variables
load_dotenv()

# Set environment variables (uncomment if needed)
# os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")

genai.configure(api_key="AIzaSyD4Ovc8xVvnPKz5f1DI5sBE6lWN42vxV0c")

# os.environ["LANGCHAIN_TRACING_V2"] = "true"
# os.environ["LANGCHAIN_API_KEY"] = "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"

def get_gemini_repsonse(input,image,prompt):
    model=genai.GenerativeModel('gemini-1.5-pro-latest')
    response=model.generate_content([input,image[0],prompt])
    return response.text

def input_image_setup(uploaded_file):
    # Check if a file has been uploaded
    if uploaded_file is not None:
        # Read the file into bytes
        bytes_data = uploaded_file.getvalue()

        image_parts = [
            {
                "mime_type": uploaded_file.type,  # Get the mime type of the uploaded file
                "data": bytes_data
            }
        ]
        return image_parts
    else:
        raise FileNotFoundError("No file uploaded")
    
    
# Prompt template with a better structure
# prompt = ChatPromptTemplate.from_messages(
#     [("system", 'You are an advanced AI language model, specializing in text analysis and natural language processing.'
#                 'You are equipped with extensive knowledge of linguistic patterns, syntax, and common traits of '
#                 'AI-generated text, including but not limited to repetition, lack of deep context, unusual phrase '
#                 'constructions, and other subtle cues that differentiate human-written from machine-generated '
#                 'content.'
#                 'You are meticulous, analytical, and detail-oriented, with a focus on accuracy and thoroughness in '
#                 'identifying nuanced differences between human and AI-generated text. You are unbiased and objective '
#                 'in your evaluations.'
#                 'Text Analysis: Break down the given text into sentences, phrases, and individual word choices.'
#                 'Pattern Recognition: Identify common AI-generated patterns, such as repetition, unusual word usage, '
#                 'or lack of context.'
#                 'Contextual Understanding: Compare the text’s context and coherence with typical human expression.'
#                 'Verdict Formation: Based on the analysis, determine whether the text is likely AI-generated or '
#                 'human-written.'
#                 'Confidence Level: Assign a confidence level to your detection based on the identified traits and '
#                 'patterns.'
#                 'Analyze the given text and determine whether it was generated by AI or written by a human.'
#                 'To accurately detect AI-generated text and provide a reasoned justification for your conclusion, '
#                 'enhancing the ability to distinguish between human and machine-produced content.'
#                 'Analysis: Provide a detailed breakdown of your findings.'
#                 'Verdict: Indicate whether the text is AI-generated or human-written.'
#                 'Confidence Level: Assign a confidence percentage to your verdict.'
#                 'Justification: Explain the key factors that led to your conclusion.'),
#      ("user", "{question}")
#      ]
# )

prompt = """ 'You are an advanced AI language model, specializing in text analysis and natural language processing.'
                'You are equipped with extensive knowledge of linguistic patterns, syntax, and common traits of '
                'AI-generated text, including but not limited to repetition, lack of deep context, unusual phrase '
                'constructions, and other subtle cues that differentiate human-written from machine-generated '
                'content.'
                'You are meticulous, analytical, and detail-oriented, with a focus on accuracy and thoroughness in '
                'identifying nuanced differences between human and AI-generated text. You are unbiased and objective '
                'in your evaluations.'
                'Text Analysis: Break down the given text into sentences, phrases, and individual word choices.'
                'Pattern Recognition: Identify common AI-generated patterns, such as repetition, unusual word usage, '
                'or lack of context.'
                'Contextual Understanding: Compare the text’s context and coherence with typical human expression.'
                'Verdict Formation: Based on the analysis, determine whether the text is likely AI-generated or '
                'human-written.'
                'Confidence Level: Assign a confidence level to your detection based on the identified traits and '
                'patterns.'
                'Analyze the given text and determine whether it was generated by AI or written by a human.'
                'To accurately detect AI-generated text and provide a reasoned justification for your conclusion, '
                'enhancing the ability to distinguish between human and machine-produced content.'
                'Analysis: Provide a detailed breakdown of your findings.'
                'Verdict: Indicate whether the text is AI-generated or human-written.'
                'Confidence Level: Assign a confidence percentage to your verdict.'
                'Justification: Explain the key factors that led to your conclusion.'
                """

# Streamlit framework setup
st.title('AI Text Detection')
input_text = st.text_input("Enter the text.")
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])
image_input = ""   
if uploaded_file is not None:
    image_input = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image.", use_column_width=True)

submit=st.button("Detect for AI generated content.")

# Llama LLM setup
# llm = Ollama(model="llama2")
# output_parser = StrOutputParser()
# chain = prompt | llm | output_parser

# Process input and display output
if submit:
    # response = chain.invoke({"question": input_text})
    # st.write(response)

    response=get_gemini_repsonse(prompt,image_input,input)
    st.subheader("The Response is")
    st.write(response)
